server:
  port: 8082
eureka:
  instance:
    appname: 8082Client
  client:
    service-url:
      defaultZone: http://192.168.1.101:10010/eureka
zuul:
  routes:
    #    8081Client-dxs: /user/**
    ycmp-onlyoffice: /ycmp-onlyoffice/**
#
#
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 10000
#ribbon:
#  ReadTimeout: 120000  #请求处理的超时时间
#  ConnectTimeout: 30000  #请求连接的超时时间




