server:
  port: 8082
eureka:
  instance:
    appname: 8082Client
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
zuul:
  routes:
    users:
      path: /get8081
      serviceId: 8081Client-dxs
      stripPrefix: true